%dev.quarkus.datasource.devservices.reuse=true
%dev.quarkus.datasource.devservices.image-name=docker.io/library/postgres:17.6
%dev.quarkus.datasource.devservices.port=5432
%dev.quarkus.datasource.devservices.db-name=coffee
%dev.quarkus.datasource.devservices.volumes."pgdata"=/var/lib/postgresql/data
%dev.quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=coffeediary
quarkus.datasource.password=coffeediary
